# Generated by Django 4.1.6 on 2023-02-10 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('picture', models.URLField()),
                ('given_name', models.CharField(blank=True, max_length=100)),
                ('email_verified', models.BooleanField(blank=True)),
                ('sub', models.CharField(max_length=100)),
            ],
        ),
    ]
