# Generated by Django 4.1.6 on 2023-02-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_user_email_verified_alter_user_picture_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='district',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='hostel_type',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='manager_contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='manager_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='place',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
