# Generated by Django 4.1.6 on 2023-02-21 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_hostel_district_alter_hostel_hostel_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('booker_name', models.CharField(blank=True, max_length=200, null=True)),
                ('contact', models.CharField(blank=True, max_length=200, null=True)),
                ('seater', models.IntegerField(blank=True, choices=[(1, 'Single Seater'), (2, 'Two Seater'), (3, 'Three Seater'), (4, 'Four Seater')], null=True)),
                ('booking_date', models.DateField(auto_now=True)),
                ('booker_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker_user', to='api.user')),
                ('hostel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_hostel', to='api.hostel')),
                ('hostel_manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.hostel')),
            ],
        ),
    ]
