# Generated by Django 4.1.6 on 2023-02-21 10:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_booking'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booker_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booker_user', to='api.user', verbose_name='booked_by'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='customer_names'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hostel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booked_hostel', to='api.hostel', verbose_name='hostel_to_book'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hostel_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.hostel', verbose_name='hostel_owner'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seater',
            field=models.IntegerField(choices=[(1, 'Single Seater'), (2, 'Two Seater'), (3, 'Three Seater'), (4, 'Four Seater')], default=1),
            preserve_default=False,
        ),
    ]
