# Generated by Django 4.1.6 on 2023-02-21 10:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_booking_booker_id_alter_booking_booker_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booker_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='customer_name'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='hostel_manager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking', to='api.user', verbose_name='hostel_owner'),
        ),
    ]
