# Generated by Django 4.1.6 on 2023-03-07 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_booking_booker_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'ordering': ('-booking_date',)},
        ),
        migrations.AddField(
            model_name='booking',
            name='booker_email',
            field=models.EmailField(default="mohammedtaukirsheikh@gmail.com", max_length=254),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='booking',
            name='booker_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='booker_user', to='api.user', verbose_name='booked_by'),
        ),
    ]
