# Generated by Django 4.1.6 on 2023-03-08 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_booking_booker_email'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='booking',
        #     name='booker_email',
        # ),
        migrations.AddField(
            model_name='booking',
            name='bookers_email',
            field=models.EmailField(blank=True, default='mohammedtaukirsheikh@gmail.com', max_length=254, null=True),
        ),
    ]
