# Generated by Django 4.1.6 on 2023-03-08 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_remove_booking_booker_email'),
    ]

    operations = [
        migrations.RunSQL('DROP TABLE Booking;'),
    ]
