# Generated by Django 4.1.6 on 2023-03-08 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20230308_2312'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='bookers_email',
        ),
    ]
