# Generated by Django 4.1.6 on 2023-03-11 06:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_booking_bookers_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRating',
            fields=[
                ('rater_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('user_rating', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=8, null=True, verbose_name='rating given by user to hostel')),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hostel', verbose_name='hostel rated by user')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_rating', to='api.user', verbose_name='hosel rater')),
            ],
        ),
    ]
