# Generated by Django 4.1.6 on 2023-03-13 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_hostel_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='room_available',
            field=models.JSONField(default={'four_seater': True, 'single_seater': True, 'three_seater': True, 'two_seater': True}),
        ),
    ]
