# Generated by Django 4.1.6 on 2023-03-13 05:40

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_hostel_room_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='room_available',
        ),
        migrations.AddField(
            model_name='hostel',
            name='rooms_available',
            field=models.JSONField(default=api.models.get_default_rooms_available, verbose_name='Rooms Available'),
        ),
    ]
