# Generated by Django 4.1.6 on 2023-03-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_remove_hostel_room_available_hostel_rooms_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hostel',
            name='rooms_available',
            field=models.JSONField(verbose_name='Rooms Available'),
        ),
    ]
