# Generated by Django 4.1.6 on 2023-03-14 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_alter_hostel_rooms_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='four_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='single_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='three_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='two_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
