# Generated by Django 4.1.6 on 2023-03-14 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_hostel_four_seater_vacant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hostel',
            name='four_seater_vacant',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='rooms_available',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='single_seater_vacant',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='three_seater_vacant',
        ),
        migrations.RemoveField(
            model_name='hostel',
            name='two_seater_vacant',
        ),
    ]
