# Generated by Django 4.1.6 on 2023-03-14 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_remove_hostel_four_seater_vacant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='hostel',
            name='four_seater_vacant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='single_seater_vacant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='three_seater_vacant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
        migrations.AddField(
            model_name='hostel',
            name='two_seater_vacant',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
