# Generated by Django 4.1.6 on 2023-03-15 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_hostel_four_seater_vacant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_manager',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='four_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='single_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='three_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AlterField(
            model_name='hostel',
            name='two_seater_vacant',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
