# Generated by Django 4.1.6 on 2023-03-15 17:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0024_user_is_manager_alter_hostel_four_seater_vacant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('review_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('review', models.TextField(blank=True, max_length=1000, null=True)),
                ('hostel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.hostel')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
            ],
        ),
    ]
