# Generated by Django 4.1.6 on 2023-03-16 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0025_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
    ]
