const SearchedHostelList=[
    {
        "hostel_id": 2,
        "image_1": "https://soaneemrana.org/____impro/1/onewebmedia/IMG_6505.JPG?etag=%2241319-55b3922e%22&sourceContentType=image%2Fjpeg&quality=85",
        "image_2": null,
        "image_3": null,
        "hostel_name": "habib",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "Sheikh",
        "manager_contact": "9824703922",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": true,
        "hot_water": true,
        "laundry": true,
        "parking": true,
        "cctv": true,
        "fan": true,
        "balcony": true,
        "map_link": "",
        "manager_id": 1
    },
    {
        "hostel_id": 3,
        "image_1": null,
        "image_2": null,
        "image_3": null,
        "hostel_name": "Habib Boys Hostel",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "ha",
        "manager_contact": "12",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": false,
        "hot_water": false,
        "laundry": false,
        "parking": true,
        "cctv": true,
        "fan": false,
        "balcony": false,
        "map_link": "",
        "manager_id": 1
    },
    {
        "hostel_id": 4,
        "image_1": null,
        "image_2": null,
        "image_3": null,
        "hostel_name": "Habib Boys Hostel",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "ha",
        "manager_contact": "12",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": false,
        "hot_water": false,
        "laundry": false,
        "parking": true,
        "cctv": true,
        "fan": false,
        "balcony": false,
        "map_link": "",
        "manager_id": 1
    },
    {
        "hostel_id": 5,
        "image_1": null,
        "image_2": null,
        "image_3": null,
        "hostel_name": "Habib Boys Hostel",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "ha",
        "manager_contact": "12",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": false,
        "hot_water": false,
        "laundry": false,
        "parking": true,
        "cctv": true,
        "fan": false,
        "balcony": false,
        "map_link": "",
        "manager_id": 1
    },
    {
        "hostel_id": 6,
        "image_1": null,
        "image_2": null,
        "image_3": null,
        "hostel_name": "Habib Boys Hostel",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "ha",
        "manager_contact": "12",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": false,
        "hot_water": false,
        "laundry": false,
        "parking": true,
        "cctv": true,
        "fan": false,
        "balcony": false,
        "map_link": "",
        "manager_id": 1
    },
    {
        "hostel_id": 7,
        "image_1": null,
        "image_2": null,
        "image_3": null,
        "hostel_name": "",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "ha",
        "manager_contact": "12",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": false,
        "hot_water": false,
        "laundry": false,
        "parking": true,
        "cctv": true,
        "fan": false,
        "balcony": false,
        "map_link": "",
        "manager_id": 1
    },
    {
        "hostel_id": 8,
        "image_1": null,
        "image_2": null,
        "image_3": null,
        "hostel_name": "",
        "hostel_type": "Boys",
        "pan_no": "",
        "district": "Kathmandu",
        "place": "Buddhanagar",
        "manager_name": "ha",
        "manager_contact": "12",
        "single_seater": null,
        "two_seater": null,
        "three_seater": null,
        "four_seater": null,
        "admission_fee": null,
        "description": "",
        "wifi": true,
        "closet": false,
        "hot_water": false,
        "laundry": false,
        "parking": true,
        "cctv": true,
        "fan": false,
        "balcony": false,
        "map_link": null,
        "manager_id": 1
    }]

    export default SearchedHostelList;